# .github/workflows/auto-update-readme.yml
name: Update README — Live Stats

on:
  push:
    paths:
      - 'proofs/**'
      - 'plots/**'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # THIS IS THE REAL FIX — WE TELL GITHUB THE EXACT VERSION
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Update proof & plot count in README
        run: |
          PROOFS=$(find proofs -type f -name "*.py" | wc -l | xargs)
          PLOTS=$(find plots -type f -name "*.png" | wc -l | xargs)
          echo "Found $PROOFS proofs and $PLOTS plots"
          
          sed -i "s/[0-9]\+ proofs/$PROOFS proofs/g" README.md
          sed -i "s/[0-9]\+ plots/$PLOTS plots/g" README.md

      - name: Commit updated README
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: update stats — $PROOFS proofs · $PLOTS plots"
          file_pattern: README.md
